"""Create blog table

Revision ID: 61a79a61cd7a
Revises: d8ee5cd1be39
Create Date: 2023-09-12 21:03:31.507123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a79a61cd7a'
down_revision: Union[str, None] = 'd8ee5cd1be39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
