"""Create blog,user,tag,post,comment table

Revision ID: d3336b071857
Revises: 91dfd6dd5110
Create Date: 2023-09-13 15:48:52.250649

"""
from typing import Sequence, Union
from sqlalchemy import Column, String, Integer, Boolean, DateTime, func

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3336b071857'
down_revision: Union[str, None] = '91dfd6dd5110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'users',
        Column('id', Integer, primary_key=True, autoincrement=True),
        Column('username', String, index=True),
        Column('email', String, unique=True, index=True),
        Column('password', String),
        Column('is_active', Boolean, default=True)
    )
    op.create_table(
        'blogs',
        Column('id', Integer, autoincrement=True, primary_key=True),
        Column('title', String(50)),
        Column('description', String(150), unique=True, index=True),
        Column('created_at', DateTime, server_default=func.now()),
        Column('updated_at', DateTime, onupdate=func.now())
    )
    op.create_table(
        'tags',
        Column('id', Integer, autoincrement=True, primary_key=True),
        Column('tag_name', String(50), unique=True)
    )
    op.create_table(
        'posts',
        Column('id', Integer, autoincrement=True, primary_key=True),
        Column('title', String(50), index=True),
        Column('body', String),
        Column('is_published', Boolean, default=False),
        Column('created_at', DateTime, server_default=func.now()),
        Column('views', Integer, default=0)
    )
    op.create_table(
        'comments',
        Column('id', Integer, autoincrement=True, primary_key=True),
        Column('body', String),
        Column('created_at', DateTime, server_default=func.now()),

    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('tags')
    op.drop_table('blogs')
    op.drop_table('users')
